<?php
$title='Growth Intelligence — '.setting('site_name','AlbaTech Solutions');
$extraHead='<style>.admin-grid{display:grid;gap:16px}.admin-grid--4{grid-template-columns:repeat(4,minmax(0,1fr))}.admin-grid--2{grid-template-columns:repeat(2,minmax(0,1fr))}.admin-card,.admin-panel{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:20px;box-shadow:0 8px 28px rgba(15,23,42,.04)}.admin-card--soft{background:#f8fafc}.admin-card__label,.admin-panel__head span,.growth-intent small,.growth-opportunity small{display:block;color:#64748b;font-size:.82rem}.admin-card__value{display:block;font-size:2rem;margin:.25rem 0}.admin-panel__head{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:14px}.admin-panel h2{margin:0;font-size:1.05rem}.growth-intent,.growth-opportunity{padding:12px 0;border-bottom:1px solid #e2e8f0}.growth-intent:last-child,.growth-opportunity:last-child{border-bottom:0}.growth-intent p{margin:0 0 5px}.growth-opportunity{display:flex;justify-content:space-between;gap:16px}.growth-tags{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.growth-tags span{font-size:.75rem;padding:5px 8px;border-radius:999px;background:#fef3c7;color:#92400e}.growth-events>div{display:flex;justify-content:space-between;padding:11px 0;border-bottom:1px solid #e2e8f0}.growth-events>div:last-child{border-bottom:0}.growth-rule{margin:0;line-height:1.7}@media(max-width:1000px){.admin-grid--4{grid-template-columns:repeat(2,minmax(0,1fr))}.admin-grid--2{grid-template-columns:1fr}}@media(max-width:600px){.admin-grid--4{grid-template-columns:1fr}.growth-opportunity{display:block}.growth-tags{justify-content:flex-start;margin-top:8px}}</style>';
ob_start();
$labels=['assistance_request_created'=>'Help requests','assistant_handoff'=>'Assistant handoffs','quote_created'=>'Quotes created','quote_accepted'=>'Quotes accepted','payment_verified'=>'Payments verified','assistance_completed'=>'Completed work','cta_get_help'=>'Get Help clicks','cta_assistant'=>'Assistant clicks','cta_whatsapp'=>'WhatsApp clicks','review_submitted'=>'Reviews'];
?>
<div class="admin-page-head">
    <div><span class="admin-kicker">Growth</span><h1>Growth Intelligence</h1><p>Understand what people read, what they ask for and which visits turn into real AlbaTech work.</p></div>
    <form method="get" style="display:flex;gap:8px;align-items:end"><label>Period<select name="days" onchange="this.form.submit()"><option value="7" <?= $days===7?'selected':'' ?>>7 days</option><option value="30" <?= $days===30?'selected':'' ?>>30 days</option><option value="90" <?= $days===90?'selected':'' ?>>90 days</option><option value="365" <?= $days===365?'selected':'' ?>>12 months</option></select></label></form>
</div>
<div class="admin-grid admin-grid--4">
<?php foreach([['Visitors',$summary['visitors'],'Unique anonymous visitors'],['Page views',$summary['page_views'],'Tracked public page views'],['Help requests',$summary['assistance_requests'],number_format($summary['request_rate'],2).'% of views'],['Payments verified',$summary['payments_verified'],number_format($summary['payment_rate'],2).'% of views']] as $card): ?><div class="admin-card"><span class="admin-card__label"><?=e($card[0])?></span><strong class="admin-card__value"><?=e((string)$card[1])?></strong><small><?=e($card[2])?></small></div><?php endforeach; ?>
</div>
<div class="admin-grid admin-grid--4" style="margin-top:16px">
<?php foreach([['Assistant handoffs',$summary['assistant_handoffs']],['Quotes accepted',$summary['quotes_accepted']],['Completed',$summary['completed']],['Request → completed',$summary['completion_rate'].'%']] as $card): ?><div class="admin-card admin-card--soft"><span class="admin-card__label"><?=e($card[0])?></span><strong class="admin-card__value"><?=e((string)$card[1])?></strong></div><?php endforeach; ?>
</div>
<div class="admin-grid admin-grid--2" style="margin-top:24px">
<section class="admin-panel"><div class="admin-panel__head"><h2>Top pages</h2><span>Last <?=$days?> days</span></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Page</th><th>Views</th><th>Visitors</th></tr></thead><tbody><?php foreach($topPages as $row): ?><tr><td><a href="<?=e($row['path'])?>" target="_blank" rel="noopener"><?=e($row['title']?:$row['path'])?></a><small style="display:block"><?=e($row['path'])?></small></td><td><?=e((string)$row['views'])?></td><td><?=e((string)$row['visitors'])?></td></tr><?php endforeach; ?><?php if(!$topPages): ?><tr><td colspan="3">No page-view data yet.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="admin-panel"><div class="admin-panel__head"><h2>Acquisition sources</h2><span>UTM + referrer host</span></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Source</th><th>Views</th><th>Visitors</th></tr></thead><tbody><?php foreach($sources as $row): ?><tr><td><?=e($row['source'])?></td><td><?=e((string)$row['views'])?></td><td><?=e((string)$row['visitors'])?></td></tr><?php endforeach; ?><?php if(!$sources): ?><tr><td colspan="3">No source data yet.</td></tr><?php endif; ?></tbody></table></div></section>
</div>
<div class="admin-grid admin-grid--2" style="margin-top:24px">
<section class="admin-panel"><div class="admin-panel__head"><h2>Service performance</h2><span>Views → requests → paid → completed</span></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Service</th><th>Views</th><th>Requests</th><th>Paid</th><th>Done</th></tr></thead><tbody><?php foreach($services as $row): ?><tr><td><a href="/services/<?=e($row['slug'])?>" target="_blank" rel="noopener"><?=e($row['name'])?></a></td><td><?=e((string)$row['views'])?></td><td><?=e((string)$row['requests'])?></td><td><?=e((string)$row['paid'])?></td><td><?=e((string)$row['completed'])?></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="admin-panel"><div class="admin-panel__head"><h2>Assistant demand</h2><span>Recent user questions</span></div><div class="growth-intents"><?php foreach($assistantIntents as $row): ?><div class="growth-intent"><p><?=e($row['message'])?></p><small><?= $row['match_count'] ? 'Matched a service' : 'No service match yet' ?> · <?=e(date('d M H:i',strtotime($row['created_at'])))?></small></div><?php endforeach; ?><?php if(!$assistantIntents): ?><p>No assistant questions yet.</p><?php endif; ?></div></section>
</div>
<div class="admin-grid admin-grid--2" style="margin-top:24px">
<section class="admin-panel"><div class="admin-panel__head"><h2>Content & SEO opportunities</h2><span>Fix these before adding more pages</span></div><div class="growth-opportunities"><?php foreach($gaps as $gap): ?><div class="growth-opportunity"><div><strong><?=e($gap['title'])?></strong><small><?=e($gap['content_type'])?> · <?=e((string)$gap['views'])?> views</small></div><div class="growth-tags"><?php if($gap['missing_title']): ?><span>Missing title</span><?php endif; ?><?php if($gap['missing_description']): ?><span>Missing description</span><?php endif; ?><?php if($gap['missing_commerce']): ?><span>Needs SEO/commercial data</span><?php endif; ?></div></div><?php endforeach; ?><?php if(!$gaps): ?><p>No obvious catalogue gaps detected.</p><?php endif; ?></div></section>
<section class="admin-panel"><div class="admin-panel__head"><h2>Tracked events</h2><span>Conversion signals</span></div><div class="growth-events"><?php foreach($events as $event): ?><div><span><?=e($labels[$event['event_name']]??$event['event_name'])?></span><strong><?=e((string)$event['total'])?></strong></div><?php endforeach; ?><?php if(!$events): ?><p>No events yet.</p><?php endif; ?></div></section>
</div>
<div class="admin-panel" style="margin-top:24px"><div class="admin-panel__head"><h2>Operating rule</h2></div><p class="growth-rule"><strong>Don't chase traffic for its own sake.</strong> Use this dashboard to find the pages and questions that create useful customer intent. Improve those pages, add missing services/content, and measure whether more visitors become paid work.</p></div>
<?php $adminContent=ob_get_clean(); require dirname(__DIR__).'/layout.php';
