<?php
$title='Quote '.$quote['quote_number'].' | AlbaTech Solutions';
$metaDescription='Review your AlbaTech digital assistance quote and confirm the next step.';
$robots='noindex, nofollow';
ob_start();
$errors=\App\Core\Session::getFlash('_errors') ?? [];$success=\App\Core\Session::getFlash('_success');
$expired=$quote['status']==='expired';
$phoneCheck=filter_var($_ENV['QUOTE_REQUIRE_PHONE_LAST4']??false,FILTER_VALIDATE_BOOLEAN);
?>
<section class="public-page-head"><div class="public-container"><span class="public-kicker">AlbaTech digital assistance</span><h1>Your quote</h1><p>Quote <strong><?= e($quote['quote_number']) ?></strong> for <?= e($quote['name']) ?>.</p></div></section>
<section class="public-container quote-public-wrap">
<?php if($success): ?><div class="alert alert-success"><?= e($success) ?></div><?php endif; ?>
<?php if($errors): ?><div class="alert alert-error"><?php foreach($errors as $list): foreach((array)$list as $err): ?><div><?= e($err) ?></div><?php endforeach; endforeach; ?></div><?php endif; ?>
<div class="quote-public-grid"><div class="quote-public-card"><div class="quote-public-meta"><span class="lead-status lead-status-<?= e($quote['status']) ?>"><?= e(ucwords(str_replace('_',' ',$quote['status']))) ?></span><?php if($quote['expires_at']): ?><span>Valid until <?= e(date('d M Y, H:i',strtotime($quote['expires_at']))) ?></span><?php endif; ?></div><div class="table-scroll"><table class="table"><thead><tr><th>Service / item</th><th>Qty</th><th>Total</th></tr></thead><tbody><?php foreach($items as $item): ?><tr><td><?= e($item['description']) ?></td><td><?= e(rtrim(rtrim(number_format((float)$item['quantity'],2,'.',''),'0'),'.')) ?></td><td>KES <?= e(number_format((float)$item['line_total'],2)) ?></td></tr><?php endforeach; ?></tbody><tfoot><tr><th colspan="2">Amount to pay</th><th>KES <?= e(number_format((float)$quote['total'],2)) ?></th></tr></tfoot></table></div><?php if($quote['note']): ?><div class="quote-note"><strong>From AlbaTech</strong><p><?= nl2br(e($quote['note'])) ?></p></div><?php endif; ?></div>
<div class="quote-public-side">
<?php if($quote['status']==='sent' && !$expired): ?><div class="quote-action-card"><span class="public-kicker">Step 1</span><h2>Accept the quote</h2><p>Confirm that you agree with the work and amount shown above. No payment is recorded by this action.</p><form method="POST" action="/quote/<?= e(rawurlencode($token)) ?>/accept"><?= csrf_field() ?><?php if($phoneCheck): ?><label>Last 4 digits of your request phone *<input name="phone_last4" maxlength="4" minlength="4" inputmode="numeric" pattern="\d{4}" required autocomplete="off"></label><?php endif; ?><button class="btn btn-primary btn-lg" type="submit">Accept quote <i class="fa-solid fa-check"></i></button></form></div><?php elseif($quote['status']==='accepted'): ?><div class="quote-action-card"><span class="public-kicker">Step 2</span><h2>Pay by M-Pesa</h2><p>Send <strong>KES <?= e(number_format((float)$quote['total'],2)) ?></strong> using the payment details AlbaTech gives you. Then enter the M-Pesa transaction code below.</p><form method="POST" action="/quote/<?= e(rawurlencode($token)) ?>/payment"><?= csrf_field() ?><?php if($phoneCheck): ?><label>Last 4 digits of your request phone *<input name="phone_last4" maxlength="4" minlength="4" inputmode="numeric" pattern="\d{4}" required autocomplete="off"></label><?php endif; ?><label>M-Pesa transaction code *<input name="mpesa_receipt" maxlength="80" required placeholder="e.g. QAB12CDE34"></label><label>Your phone <span class="muted-small">optional</span><input name="payer_phone" maxlength="30" inputmode="tel" placeholder="07XXXXXXXX"></label><label>Note <span class="muted-small">optional</span><textarea name="customer_note" maxlength="500" rows="3" placeholder="Anything we should know?"></textarea></label><button class="btn btn-primary btn-lg" type="submit">Submit payment for verification</button></form></div><?php elseif($quote['status']==='paid'): ?><div class="quote-action-card"><span class="public-kicker">Payment confirmed</span><h2>Thank you.</h2><p>Your payment has been verified. AlbaTech can now proceed with the agreed assistance.</p></div><?php elseif($expired): ?><div class="quote-action-card"><span class="public-kicker">Quote expired</span><h2>This quote is no longer active.</h2><p>Please contact AlbaTech if you still need the service.</p></div><?php else: ?><div class="quote-action-card"><h2>Quote status</h2><p>This quote is currently <strong><?= e($quote['status']) ?></strong>. Contact AlbaTech if you need clarification.</p></div><?php endif; ?>
<div class="quote-public-trust"><i class="fa-solid fa-shield-halved"></i><div><strong>Important</strong><p>AlbaTech is an independent digital assistance business. Never share your M-Pesa PIN, OTP or banking password with us.</p></div></div>
</div></div></section>
<?php $pageContent=ob_get_clean(); require dirname(__DIR__).'/layout.php';
