<?php declare(strict_types = 1);

// phpinternal-PHPStan\BetterReflection\Reflection\ReflectionConstant-E_CORE_ERROR
return \PHPStan\Cache\CacheItem::__set_state(array(
   'variableKey' => 'v2-6.70.0.3-dev-master@709e512-8.2.12',
   'data' => 
  array (
    'locatedSource' => 
    array (
      'class' => 'PHPStan\\BetterReflection\\SourceLocator\\Located\\InternalLocatedSource',
      'data' => 
      array (
        'name' => 'E_CORE_ERROR',
        'filename' => 'phpstorm-stubs:Core/Core_d.stub',
        'extensionName' => 'Core',
        'aliasName' => NULL,
      ),
    ),
    'name' => 'E_CORE_ERROR',
    'shortName' => 'E_CORE_ERROR',
    'value' => 
    array (
      'code' => '16',
      'attributes' => 
      array (
        'startLine' => 8,
        'endLine' => 8,
        'startTokenPos' => 9,
        'startFilePos' => 232,
        'endTokenPos' => 9,
        'endFilePos' => 233,
      ),
    ),
    'docComment' => '/**
 * Fatal errors that occur during PHP\'s initial startup. This is like an
 * <b>E_ERROR</b>, except it is generated by the core of PHP.
 * @link https://php.net/manual/en/errorfunc.constants.php
 */',
    'attributes' => 
    array (
    ),
    'startLine' => 8,
    'endLine' => 8,
    'startColumn' => 1,
    'endColumn' => 26,
    'namespace' => NULL,
  ),
));