<?php $title=$requestItem['request_number'].' | AlbaTech'; ob_start(); ?>
<section class="customer-page-head"><a href="/account/requests" class="back-link">← My requests</a><span class="eyebrow"><?= e($requestItem['request_number']) ?></span><h1><?= e($requestItem['service_name'] ?: ucwords(str_replace('_',' ',$requestItem['category']))) ?></h1><p>Current status: <strong><?= e(str_replace('_',' ',$requestItem['status'])) ?></strong></p></section>
<div class="customer-detail-grid">
    <section class="card"><span class="eyebrow">Your request</span><p><?= nl2br(e($requestItem['message'])) ?></p><?php if($requestItem['due_at']): ?><p class="muted-small">Target date: <?= e(date('d M Y, H:i',strtotime($requestItem['due_at']))) ?></p><?php endif; ?></section>
    <section class="card"><span class="eyebrow">Quote</span><?php if(!$quote): ?><h2>No quote yet</h2><p class="muted-small">We'll send one here when your request needs a quote.</p><?php else: ?><h2>KES <?= e(number_format((float)$quote['total'],2)) ?></h2><p><?= e($quote['quote_number']) ?> · <?= e($quote['status']) ?></p><a class="btn btn-secondary" href="/account/quotes/<?= (int)$quote['id'] ?>">View quote</a><?php endif; ?></section>
    <?php if($payment && $receiptUrl): ?><section class="card"><span class="eyebrow">Verified payment</span><h2>KES <?= e(number_format((float)$payment['amount'],2)) ?></h2><p class="muted-small">M-Pesa: <?= e($payment['mpesa_receipt'] ?: 'Verified') ?></p><a class="btn btn-secondary" href="<?= e($receiptUrl) ?>" target="_blank" rel="noopener">View receipt</a></section><?php endif; ?>
    <section class="card customer-wide"><span class="eyebrow">Updates</span><h2>Progress from AlbaTech</h2><?php if(!$updates): ?><p class="muted-small">No updates yet.</p><?php else: foreach($updates as $update): ?><article class="customer-update"><span class="eyebrow"><?= e($update['update_type']) ?> · <?= e(date('d M Y, H:i',strtotime($update['created_at']))) ?></span><p><?= nl2br(e($update['message'])) ?></p></article><?php endforeach; endif; ?></section>
    <section class="card customer-wide"><span class="eyebrow">Work checklist</span><h2>Progress</h2><?php if(!$tasks): ?><p class="muted-small">Work details will appear here as they are prepared.</p><?php else: foreach($tasks as $task): ?><div class="customer-task"><i class="fa-solid <?= $task['status']==='completed'?'fa-circle-check':'fa-circle' ?>"></i><span><?= e($task['title']) ?></span><span class="muted-small"><?= e(str_replace('_',' ',$task['status'])) ?></span></div><?php endforeach; endif; ?></section>
</div>
<?php if($reviewUrl && $requestItem['status']==='completed'): ?><div class="customer-review-callout"><h2>How did we do?</h2><p>Your work is complete. We'd appreciate a quick review.</p><a class="btn btn-primary" href="<?= e($reviewUrl) ?>">Leave a review</a></div><?php endif; ?>
<?php $customerContent=ob_get_clean(); require __DIR__.'/layout.php'; ?>
